### PR TITLE
Fix Update Behaviour

### PR DESCRIPTION
**Pull request by vpuri3**
- [x] fix https://github.com/SciML/SciMLOperators.jl/issues/56
- [x] fix https://github.com/SciML/SciMLOperators.jl/issues/66
- [x] take a look at other `update_coefficients!` stuff marked with `# TODO`
- [x] fix https://github.com/SciML/SciMLOperators.jl/issues/71
- [x] overlaod `Base.conj, Base.adjoint` everywhere with lazy update rule

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Add tests

**Comment by vpuri3** [comment]
yep

**Comment by vpuri3** [comment]
need tests now

**Comment by vpuri3** [comment]
@ChrisRackauckas this is done

**Review by ChrisRackauckas — APPROVED** [review]

**Pull request merged**
