### PR TITLE
Adjoint, transpose, diagonal operators

### PR DESCRIPTION
**Pull request by vpuri3**
closes https://github.com/SciML/SciMLOperators.jl/issues/12 , https://github.com/SciML/SciMLOperators.jl/issues/14

### CODE REVIEW

**Comment by vpuri3** [comment]
i dont need CI to run after every commit. is that possible to do?

**Comment by ChrisRackauckas** [comment]
Put `[ci-skip]` at the start of the commit messsage.

**Comment by vpuri3** [comment]
@ChrisRackauckas good to go

**Comment by vpuri3** [comment]
@danielwe this should have all the functionality one needs

**Pull request merged**
