### PR TITLE
Fix forward and inverse application in FFTW tutorial

### PR DESCRIPTION
**Pull request by ErikQQY**
Fix: #228 

## Checklist

- [x] Documentation fix

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Can you turn this into an `@example` so it tests the runs?

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
Needs to update docs project.toml

**Comment by vpuri3** [comment]
rerunning CI

**Comment by ErikQQY** [comment]
Documentation CI is fine, the other CI failed since #226

**Pull request merged**
