### PR TITLE
clean up convert-based fallbacks

### PR DESCRIPTION
**Pull request by vpuri3**
fix https://github.com/SciML/LinearSolve.jl/actions/runs/5417914034/jobs/9849418672?pr=337#step:6:13263

### CODE REVIEW

**Comment by vpuri3** [comment]
with this branch,
```julia
julia> using SciMLOperators, LinearAlgebra

julia> a = MatrixOperator(rand(4,4))

julia> b = a + a * a \ a

julia> issymmetric(b)
┌ Warning: using convert-based fallback in issymmetric.
└ @ SciMLOperators ~/.julia/dev/SciMLOperators/src/interface.jl:387
false

julia> sum(Base.Fix2(*, 2), (a,a); init = a)
(MatrixOperator(4 × 4) + ScalarOperator(2) * MatrixOperator(4 × 4) + ScalarOperator(2) * MatrixOperator(4 × 4))

julia> prod(Base.Fix2(*, 2), (a,a); init = a)
(MatrixOperator(4 × 4) * ScalarOperator(2) * MatrixOperator(4 × 4) * ScalarOperator(2) * MatrixOperator(4 × 4))
```

**Comment by ChrisRackauckas** [comment]
The downstream tests are still failing on this merge? https://github.com/SciML/SciMLOperators.jl/actions/runs/5437055376/jobs/9887334855#step:6:966

**Comment by vpuri3** [comment]
weird taking a look

**Comment by vpuri3** [comment]
Thanks for pointing this out. I was wrong to remove fallback methods for `sum, prod`. Let me fix that.

**Comment by vpuri3** [comment]
I made the mistake of confusing the methods

```julia
sum(f, (A, B); init) # returns lazy AddedOperator
```
with
```julia
sum(A::AbstractArray; dims) # reduces with sum across dims
```
I added back the removed methods in #209 with an example.

**Pull request merged**
