### PR TITLE
[WIP] chain rules

### PR DESCRIPTION
**Pull request by vpuri3**

### CODE REVIEW

**Comment by vpuri3** [comment]
should rules instead be defined for `L(u, p, t)`, `L(du, u, p, t)`?

**Comment by vpuri3** [comment]
ref https://github.com/JuliaDiff/ChainRules.jl/blob/main/src/rulesets/Base/arraymath.jl#L18-L41

**Comment by vpuri3** [comment]
`AffineOperator`, `FunctionOperator` might need special handling since adjoint may not be defined

**Comment by vpuri3** [comment]
might need mutating updates idk https://github.com/SciML/SciMLOperators.jl/blob/master/src/interface.jl#L20-L30

**Comment by vpuri3** [comment]
without any rules,
```julia
julia> u=rand(4); f = M -> sum(M * u);

julia> Zygote.gradient(f, MatrixOperator(rand(4,4)))[1]
4×4 Matrix{Float64}:
 0.645072  0.703859  0.672197  0.0561734
 0.645072  0.703859  0.672197  0.0561734
 0.645072  0.703859  0.672197  0.0561734
 0.645072  0.703859  0.672197  0.0561734
```
so far so good.
```
julia> Zygote.gradient(f, DiagonalOperator(rand(4)))[1]
4×4 Matrix{Float64}:
 0.645072  0.703859  0.672197  0.0561734
 0.645072  0.703859  0.672197  0.0561734
 0.645072  0.703859  0.672197  0.0561734
 0.645072  0.703859  0.672197  0.0561734
```
this fill for `DiagonalOperator` would kill applications with large `N`.

**Comment by vpuri3** [comment]
further
```julia
julia> F=AffineOperator(rand(4,4), rand(4,4), rand(4));

julia> f(F)
7.214805149913472

julia> Zygote.gradient(f, F)[1]
ERROR: StackOverflowError:
Stacktrace:
 [1] *(L::SciMLOperators.AdjointOperator{Float64, AffineOperator{Float64, MatrixOperator{Float64, Matrix{Float64}, typeof(SciMLOperators.DEFAULT_UPDATE_FUNC)}, MatrixOperator{Float64, Matrix{Float64}, typeof(SciMLOperators.DEFAULT_UPDATE_FUNC)}, Vector{Float64}, Vector{Float64}, typeof(SciMLOperators.DEFAULT_UPDATE_FUNC)}}, u::FillArrays.Fill{Float64, 1, Tuple{Base.OneTo{Int64}}})
   @ SciMLOperators ~/.julia/dev/SciMLOperators/src/multidim.jl:9
 [2] *(L::SciMLOperators.AdjointOperator{Float64, AffineOperator{Float64, MatrixOperator{Float64, Matrix{Float64}, typeof(SciMLOperators.DEFAULT_UPDATE_FUNC)}, MatrixOperator{Float64, Matrix{Float64}, typeof(SciMLOperators.DEFAULT_UPDATE_FUNC)}, Vector{Float64}, Vector{Float64}, typeof(SciMLOperators.DEFAULT_UPDATE_FUNC)}}, u::FillArrays.Fill{Float64, 1, Tuple{Base.OneTo{Int64}}}) (repeats 79983 times)
   @ SciMLOperators ~/.julia/dev/SciMLOperators/src/multidim.jl:16

```

**Comment by ChrisRackauckas** [comment]
You need to define the ProjectTo

**Comment by vpuri3** [comment]
that would still form the `NxN` matrix

**Comment by vpuri3** [comment]
commit history is v messy lemme just get a new branch

**Pull request closed without merging**
