### PR TITLE
allow functionoperator (batch = false) to accept/return vec'd arrays

### PR DESCRIPTION
**Pull request by vpuri3**
@ChrisRackauckas 

with this branch,

```julia
julia> f(u, p, t) = 2u; f(v, u, p, t) = mul!(v, 2, u);                                                                                                               [30/1927]
                                           
julia> F = FunctionOperator(f, ones(4, 4));
                                           
julia> F * ones(4, 4)
4×4 Matrix{Float64}:
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0                        

julia> F * vec(ones(4, 4))
16-element Vector{Float64}:
 2.0
 2.0
 2.0
 2.0
 2.0
...
julia> mul!(zeros(16), F, ones(16))
16-element Vector{Float64}:
 2.0
 2.0
 2.0
 2.0
 2.0
...

```

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Should we just remove the `vec` in that spot of OrdinaryDiffEq if it's hitting an operator?

**Comment by vpuri3** [comment]
We will remove the entire WOperator object evenetually.

The idea behind this PR is that we should support vec'd arrays anyway because one or the other downstream packages would use it. I've added warnings, docs etc all over the place as well. So after this PR, I believe we will be hitting all use cases and this package will be as versatile as it gets.

**Comment by vpuri3** [comment]
We should also move preconditioner tests to interfaceII in ODE.jl

**Comment by vpuri3** [comment]
BTW the failing test in `preconditioner.jl` is passing now

**Review by ChrisRackauckas — APPROVED** [review]

**Pull request merged**
